<?php
require_once("config/config.php");
require_once("config/db.php");
require_once root('includes/header.php');
?>

<div class="container-fluid bg-info" style="height:20vh">
  <div class="row px-5">
    <div class="col-sm-12">
      <h1 class="p-5 text-white ">About Us</h1>
    </div>

    <div class="row d-flex justify-content-center">
      <div class="col-sm-10">
        <div class="card card-body">
          <p style="font-size: 1.2rem;">
            Digital Assignment is a software that helps the teachers to schedule tasks and assign them to the respective students. Authorized teacher can get the benefits of creating assignments with ease and also they can provide the necessary feedbacks to the students and can provide marking to the students. Additionally, deadlines are provided to the students, and after the submission, they are evaluated by the teachers.The feedbacks generated by the teacher can be viewed by the students.
          </p>
        </div>
      </div>
    </div>

    <div class="row my-5">
      <div class="col-sm-12">
        <h2>Why digital Assignment?</h2>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque deserunt praesentium odit aliquam quidem velit nisi ducimus, consequatur quam laboriosam voluptas, accusantium iste sed temporibus unde! Omnis perspiciatis rem ab.
          Asperiores aliquid sequi sed delectus sit obcaecati dolores consectetur placeat sapiente cumque, porro dicta repellat vitae eius dolore, consequuntur at ullam aspernatur non corporis nulla? Autem voluptates libero sequi itaque?
          Rerum maiores minima quae nulla, recusandae reiciendis nihil ut animi voluptates ipsa hic blanditiis corporis aperiam, dolorem consectetur quidem aliquid laudantium deserunt vel? Amet, dolor sint saepe ipsam dignissimos dolores!
          
        </p>
      </div>
    </div>

  </div>
  <?php
  require_once root('includes/footer.php');
  ?>